- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "ansible provision"
    minutes: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/RMArthur/ansible.git > /dev/null"
